return {
    -- Axes (Wood R Us — Thom)
    { Name = "Basic Hatchet", Image = "Axe_Basic_Hatchet.png", Price = 12, BoxItemName = "BasicHatchet", Store = "WoodRUs" },
    { Name = "Plain Axe", Image = "Axe_Plain.png", Price = 90, BoxItemName = "Axe1", Store = "WoodRUs" },
    { Name = "Steel Axe", Image = "Axe_Steel.png", Price = 190, BoxItemName = "Axe2", Store = "WoodRUs" },
    { Name = "Hardened Axe", Image = "Axe_Hardened.png", Price = 550, BoxItemName = "Axe3", Store = "WoodRUs" },
    { Name = "Silver Axe", Image = "Axe_Silver.png", Price = 2040, BoxItemName = "SilverAxe", Store = "WoodRUs" },
    -- Conveyors (Bob's Shack — Bob)
    { Name = "Straight Conveyor", Image = "Conveyor_Straight.png", Price = 80, BoxItemName = "StraightConveyor", Store = "WoodRUs" },
    { Name = "Turn Conveyor", Image = "Conveyor_Turn.png", Price = 100, BoxItemName = "TightTurnConveyor", Store = "WoodRUs" },
    { Name = "Tilted Conveyor", Image = "Conveyor_Tilted.png", Price = 95, BoxItemName = "TiltConveyor", Store = "WoodRUs" },
    { Name = "Funnel Conveyor", Image = "Conveyor_Funnel.png", Price = 60, BoxItemName = "ConveyorFunnel", Store = "WoodRUs" },
    { Name = "SwitchConveyor", Image = "Conveyor_Switch.png", Price = 320, BoxItemName = "ConveyorSwitch", Store = "WoodRUs" },
    { Name = "Straight Conveyor Switch Left", Image = "Conveyor_Straight_Switch_Left.png", Price = 480, BoxItemName = "StraightSwitchConveyorLeft", Store = "WoodRUs" },
    { Name = "Straight Conveyor Switch Right", Image = "Conveyor_Straight_Switch_Right.png", Price = 480, BoxItemName = "StraightSwitchConveyorRight", Store = "WoodRUs" },
    { Name = "Sweeper Conveyor", Image = "Conveyor_Sweeper.png", Price = 430, BoxItemName = "LogSweeper", Store = "WoodRUs" },
    { Name = "Conveyor Supports", Image = "Conveyor_Supports.png", Price = 12, BoxItemName = "ConveyorSupports", Store = "WoodRUs" },
    { Name = "Turn Conveyor Supports", Image = "Conveyor_Turn_Supports.png", Price = 20, BoxItemName = "TightTurnConveyorSupports", Store = "WoodRUs" },
    -- Sawmills (Bob's Shack — Bob)
    { Name = "Shabby Sawmill", Image = "Sawmill_Shabby.png", Price = 130, BoxItemName = "Sawmill", Store = "WoodRUs" },
    { Name = "Fair Sawmill", Image = "Sawmill_Fair.png", Price = 1600, BoxItemName = "Sawmill2", Store = "WoodRUs" },
    { Name = "Sawmax 01", Image = "Sawmax_01.png", Price = 11000, BoxItemName = "Sawmill3", Store = "WoodRUs" },
    { Name = "Sawmax 02", Image = "Sawmax_02.png", Price = 22500, BoxItemName = "Sawmill4", Store = "WoodRUs" },
    { Name = "Sawmax 02L", Image = "Sawmax_02L.png", Price = 86500, BoxItemName = "Sawmill4L", Store = "WoodRUs" },
    { Name = "Chop Saw", Image = "Chop_Saw.png", Price = 12200, BoxItemName = "ChopSaw", Store = "WoodRUs" },
    -- Logic (Lincoln's Logic — Lincoln)
    { Name = "Wire", Image = "Wire.png", Price = 205, BoxItemName = "Wire", Store = "WoodRUs" },
    { Name = "Maple Icicle Wire", Image = "Wire_Icicle_Maple.png", Price = 1450, BoxItemName = "IcicleWireMaple", Store = "FurnitureStore" },
    { Name = "Candy Cane Icicle Wire", Image = "Wire_Icicle_Candy_Cane.png", Price = 1050, BoxItemName = "IcicleWireCandy", Store = "FurnitureStore" },
    { Name = "Spooky Icicle Wire", Image = "Wire_Icicle_Spooky.png", Price = 910, BoxItemName = "IcicleWireHalloween", Store = "FurnitureStore" },
    { Name = "Scary Icicle Wire", Image = "Wire_Icicle_Scary.png", Price = 910, BoxItemName = "IcicleWireHalloweenGreen", Store = "FurnitureStore" },
    { Name = "Amber Icicle Wire", Image = "wwwwwwww.png", Price = 750, BoxItemName = "IcicleWireAmber", Store = "FurnitureStore" },
    { Name = "Blue Icicle Wire", Image = "wwwwwwww.png", Price = 750, BoxItemName = "IcicleWireBlue", Store = "FurnitureStore" },
    { Name = "Green Icicle Wire", Image = "wwwwwwww.png", Price = 750, BoxItemName = "IcicleWireGreen", Store = "FurnitureStore" },
    { Name = "Red Icicle Wire", Image = "wwwwwwww.png", Price = 750, BoxItemName = "IcicleWireRed", Store = "FurnitureStore" },
    { Name = "Button", Image = "Button.png", Price = 320, BoxItemName = "Button0", Store = "WoodRUs" },
    { Name = "Lever", Image = "Lever.png", Price = 520, BoxItemName = "Lever0", Store = "WoodRUs" },
    { Name = "Pressure Plate", Image = "Pressure_Plate.png", Price = 640, BoxItemName = "PressurePlate", Store = "WoodRUs" },
    { Name = "Signal Inverter", Image = "Signal_Inverter.png", Price = 200, BoxItemName = "GateNOT", Store = "LogicStore" },
    { Name = "Signal Substain", Image = "Signal_Substain.png", Price = 520, BoxItemName = "SignalSustain", Store = "LogicStore" },
    { Name = "Signal Delay", Image = "Signal_Delay.png", Price = 520, BoxItemName = "SignalDelay", Store = "LogicStore" },
    { Name = "AND Gate", Image = "And_Gate.png", Price = 260, BoxItemName = "GateAND", Store = "LogicStore" },
    { Name = "OR Gate", Image = "OR_Gate.png", Price = 260, BoxItemName = "GateOR", Store = "LogicStore" },
    { Name = "XOR Gate", Image = "XOR_Gate.png", Price = 260, BoxItemName = "GateXOR", Store = "LogicStore" },
    { Name = "Clock Switch", Image = "Clock_Switch.png", Price = 902, BoxItemName = "ClockSwitch", Store = "LogicStore" },
    { Name = "Wood Detector", Image = "Wood_Detector.png", Price = 11300, BoxItemName = "WoodChecker", Store = "LogicStore" },
    { Name = "Laser", Image = "Laser.png", Price = 11300, BoxItemName = "Laser", Store = "LogicStore" },
    { Name = "Laser Detector", Image = "Laser_Detector.png", Price = 3200, BoxItemName = "LaserReceiver", Store = "LogicStore" },
    { Name = "Hatch", Image = "Hatch.png", Price = 830, BoxItemName = "Hatch", Store = "LogicStore" },
    -- Vehicles (Jenny's Cars — Jenny)
    { Name = "Utility Truck", Image = "Vehicle_Utility_Truck.png", Price = 400, BoxItemName = "UtilityTruck", Store = "WoodRUs" },
    { Name = "Utility Truck XL", Image = "Vehicle_Utility_Truck_XL.png", Price = 5000, BoxItemName = "UtilityTruck2", Store = "CarStore" },
    { Name = "Pickup Truck", Image = "Vehicle_Pickup_Truck.png", Price = 19000, BoxItemName = "Pickup1", Store = "CarStore" },
    { Name = "Small Trailer", Image = "Vehicle_Trailer_Small.png", Price = 1800, BoxItemName = "SmallTrailer", Store = "CarStore" },
    { Name = "Large Trailer", Image = "Vehicle_Trailer_Large.png", Price = 13000, BoxItemName = "Trailer2", Store = "CarStore" },
    -- Furniture
    { Name = "Armchair", Image = "Furniture_Armchair.png", Price = 140, BoxItemName = "Seat_Armchair", Store = "FurnitureStore" },
    { Name = "Loveseat", Image = "Furniture_Loveseat.png", Price = 200, BoxItemName = "Seat_Loveseat", Store = "FurnitureStore" },
    { Name = "couch", Image = "Furniture_Couch.png", Price = 320, BoxItemName = "Seat_Armchair", Store = "FurnitureStore" },
    { Name = "Bed", Image = "Furniture_Bed.png", Price = 250, BoxItemName = "Bed1", Store = "FurnitureStore" },
    { Name = "Large Bed", Image = "Furniture_Large_Bed.png", Price = 350, BoxItemName = "Bed1", Store = "FurnitureStore" },
    { Name = "Floor Lamp", Image = "Furniture_Floor_Lamp.png", Price = 110, BoxItemName = "FloorLamp1", Store = "FurnitureStore" },
    { Name = "Lamp", Image = "Furniture_Lamp.png", Price = 90, BoxItemName = "Lamp1", Store = "FurnitureStore" },
    { Name = "Wall Light", Image = "Furniture_Wall_Light.png", Price = 90, BoxItemName = "WallLight1", Store = "FurnitureStore" },
    { Name = "Flood Light", Image = "Furniture_Flood_Light.png", Price = 90, BoxItemName = "WallLight2", Store = "FurnitureStore" },
    { Name = "Refridgerator", Image = "Furniture_Refridgerator.png", Price = 310, BoxItemName = "Refridgerator", Store = "FurnitureStore" },
    { Name = "Stove", Image = "Furniture_Stove.png", Price = 340, BoxItemName = "Stove", Store = "FurnitureStore" },
    { Name = "Dishwasher", Image = "Furniture_Dishwasher.png", Price = 380, BoxItemName = "Dishwasher", Store = "FurnitureStore" },
    { Name = "Toilet", Image = "Furniture_Toilet.png", Price = 90, BoxItemName = "Toilet", Store = "FurnitureStore" },
    { Name = "Firework Launcher", Image = "Firework_Launcher.png", Price = 7500, BoxItemName = "FireworkLauncher", Store = "FurnitureStore" },
    { Name = "Glass Door", Image = "Glass_Door.png", Price = 720, BoxItemName = "GlassDoor1", Store = "FurnitureStore" },
    { Name = "Large Glass Pane", Image = "Glass_Pane_Large.png", Price = 550, BoxItemName = "GlassPane4", Store = "FurnitureStore" },
    { Name = "Glass Pane", Image = "Glass_Pane.png", Price = 220, BoxItemName = "GlassPane3", Store = "FurnitureStore" },
    { Name = "Small Glass Pane", Image = "Glass_Pane_Small.png", Price = 50, BoxItemName = "GlassPane2", Store = "FurnitureStore" },
    { Name = "Tiny Glass Pane", Image = "Glass_Pane_Tiny.png", Price = 12, BoxItemName = "GlassPane1", Store = "FurnitureStore" },
    -- Paintings
    { Name = "Outdoor Water Sketch Painting", Image = "Painting_Outdoor_Watercolor_Sketch.png", Price = 6, BoxItemName = "wwwwwww", Store = "ArtStore" },
    { Name = "Disturbed Painting", Image = "Painting_Disturbed.png", Price = 2006, BoxItemName = "wwwwwww", Store = "ArtStore" },
    { Name = "Title Uknown Painting", Image = "Painting_Title_Uknown.png", Price = 5980, BoxItemName = "wwwwwww", Store = "ArtStore" },
    { Name = "Arctic Light Painting", Image = "Painting_Arctic_Light.png", Price = 16000, BoxItemName = "wwwwwww", Store = "ArtStore" },
    { Name = "Gloomy Seascape At Dusk Painting", Image = "Painting_Gloomy_Seascape_At_Dusk.png", Price = 16800, BoxItemName = "wwwwwww", Store = "ArtStore" },
    { Name = "The Lonely Giraffe Painting", Image = "Painting_The_Lonely_Giraffe.png", Price = 26800, BoxItemName = "wwwwwww", Store = "ArtStore" },
    { Name = "Pineapple Painting", Image = "Painting_Pineapple.png", Price = 2406000, BoxItemName = "wwwwwww", Store = "ArtStore" },
    -- Other (Bob's Shack — Bob)
    { Name = "Sandbag", Image = "Sandbag.png", Price = 1600, BoxItemName = "BagOfSand", Store = "WoodRUs" },
    { Name = "Can Of Worms", Image = "Can_Of_Worms.png", Price = 3200, BoxItemName = "CanOfWorms", Store = "ShackShop" },
    { Name = "Ligh Bulb", Image = "Light_Bulb.png", Price = 2600, BoxItemName = "LightBulb", Store = "FurnitureStore" },
    { Name = "Dynamite", Image = "Dynamite.png", Price = 220, BoxItemName = "Dynamite", Store = "ShackShop" },
    { Name = "Worklight", Image = "Worklight.png", Price = 80, BoxItemName = "WorkLight", Store = "WoodRUs" },
}
--{ Name = "", Image = ".png", Price = , BoxItemName = "", Store = "" },
